import type { Metadata } from "next";

import { Inter } from "next/font/google";

import "./globals.css";

import Theme from "@/components/providers/ThemeProvider";

const interSans = Inter({
  variable: "--font-geist-sans",

  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Typersi",

  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="pl" suppressHydrationWarning>
      <body
        className={`
 ${interSans.variable}

 antialiased

 min-h-screen

 bg-background

 overflow-y-auto

 overflow-x-hidden
 `}
      >
        <Theme>{children}</Theme>
      </body>
    </html>
  );
}
