import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import BottomNavbar from "@/components/bottom-navbar/BottomNavbar";

const interSans = Inter({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Typersi",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="pl">
      <body
        className={`${interSans.variable} antialiased w-svw min-h-svh bg-lightGray`}
      >
        <div className="w-svw p-8 h-svh">{children}</div>
        <BottomNavbar />
      </body>
    </html>
  );
}
