
POST http://localhost:8001/api/admin/matches
Content-Type: application/json
Authorization: xxxxxxxx

{"matches":[
    {"date": "2026-06-11",
    "time": "13:00 UTC-6",
    "team1": "Meksyk",
    "team2": "RPA",
    "group": "A"},
   {"date": "2026-06-11",
    "time": "20:00 UTC-6",
    "team1": "Korea Południowa",
    "team2": "Czechy",
    "group": "A"},
   {"date": "2026-06-18",
    "time": "12:00 UTC-4",
    "team1": "Czechy",
    "team2": "RPA",
    "group": "A"},
   {"date": "2026-06-18",
    "time": "19:00 UTC-6",
    "team1": "Meksyk",
    "team2": "Korea Południowa",
    "group": "A"},
   {"date": "2026-06-24",
    "time": "19:00 UTC-6",
    "team1": "Czechy",
    "team2": "Meksyk",
    "group": "A"},
   {"date": "2026-06-24",
    "time": "19:00 UTC-6",
    "team1": "RPA",
    "team2": "Korea Południowa",
    "group": "A"},
   {"date": "2026-06-12",
    "time": "15:00 UTC-4",
    "team1": "Kanada",
    "team2": "Bośnia i Hercegowina",
    "group": "B"},
   {"date": "2026-06-13",
    "time": "12:00 UTC-7",
    "team1": "Katar",
    "team2": "Szwajcaria",
    "group": "B"},
   {"date": "2026-06-18",
    "time": "12:00 UTC-7",
    "team1": "Szwajcaria",
    "team2": "Bośnia i Hercegowina",
    "group": "B"},
   {"date": "2026-06-18",
    "time": "15:00 UTC-7",
    "team1": "Kanada",
    "team2": "Katar",
    "group": "B"},
   {"date": "2026-06-24",
    "time": "12:00 UTC-7",
    "team1": "Szwajcaria",
    "team2": "Kanada",
    "group": "B"},
   {"date": "2026-06-24",
    "time": "12:00 UTC-7",
    "team1": "Bośnia i Hercegowina",
    "team2": "Katar",
    "group": "B"},
   {"date": "2026-06-13",
    "time": "18:00 UTC-4",
    "team1": "Brazylia",
    "team2": "Maroko",
    "group": "C"},
   {"date": "2026-06-13",
    "time": "21:00 UTC-4",
    "team1": "Haiti",
    "team2": "Szkocja",
    "group": "C"},
   {"date": "2026-06-19",
    "time": "18:00 UTC-4",
    "team1": "Szkocja",
    "team2": "Maroko",
    "group": "C"},
   {"date": "2026-06-19",
    "time": "21:00 UTC-4",
    "team1": "Brazylia",
    "team2": "Haiti",
    "group": "C"},
   {"date": "2026-06-24",
    "time": "18:00 UTC-4",
    "team1": "Szkocja",
    "team2": "Brazylia",
    "group": "C"},
   {"date": "2026-06-24",
    "time": "18:00 UTC-4",
    "team1": "Maroko",
    "team2": "Haiti",
    "group": "C"},
   {"date": "2026-06-12",
    "time": "18:00 UTC-7",
    "team1": "USA",
    "team2": "Paragwaj",
    "group": "D"},
   {"date": "2026-06-13",
    "time": "21:00 UTC-7",
    "team1": "Australia",
    "team2": "Turcja",
    "group": "D"},
   {"date": "2026-06-19",
    "time": "12:00 UTC-7",
    "team1": "USA",
    "team2": "Australia",
    "group": "D"},
   {"date": "2026-06-19",
    "time": "21:00 UTC-7",
    "team1": "Turcja",
    "team2": "Paragwaj",
    "group": "D"},
   {"date": "2026-06-25",
    "time": "19:00 UTC-7",
    "team1": "Turcja",
    "team2": "USA",
    "group": "D"},
   {"date": "2026-06-25",
    "time": "19:00 UTC-7",
    "team1": "Paragwaj",
    "team2": "Australia",
    "group": "D"},
   {"date": "2026-06-14",
    "time": "12:00 UTC-5",
    "team1": "Niemcy",
    "team2": "Curacao",
    "group": "E"},
   {"date": "2026-06-14",
    "time": "19:00 UTC-4",
    "team1": "Wybrzeże Kości Słoniowej",
    "team2": "Ekwador",
    "group": "E"},
   {"date": "2026-06-20",
    "time": "16:00 UTC-4",
    "team1": "Niemcy",
    "team2": "Wybrzeże Kości Słoniowej",
    "group": "E"},
   {"date": "2026-06-20",
    "time": "19:00 UTC-5",
    "team1": "Ekwador",
    "team2": "Curacao",
    "group": "E"},
   {"date": "2026-06-25",
    "time": "16:00 UTC-4",
    "team1": "Curacao",
    "team2": "Wybrzeże Kości Słoniowej",
    "group": "E"},
   {"date": "2026-06-25",
    "time": "16:00 UTC-4",
    "team1": "Ekwador",
    "team2": "Niemcy",
    "group": "E"},
   {"date": "2026-06-14",
    "time": "15:00 UTC-5",
    "team1": "Holandia",
    "team2": "Japonia",
    "group": "F"},
   {"date": "2026-06-14",
    "time": "20:00 UTC-6",
    "team1": "Szwecja",
    "team2": "Tunezja",
    "group": "F"},
   {"date": "2026-06-20",
    "time": "12:00 UTC-5",
    "team1": "Holandia",
    "team2": "Szwecja",
    "group": "F"},
   {"date": "2026-06-20",
    "time": "22:00 UTC-6",
    "team1": "Tunezja",
    "team2": "Japonia",
    "group": "F"},
   {"date": "2026-06-25",
    "time": "18:00 UTC-5",
    "team1": "Japonia",
    "team2": "Szwecja",
    "group": "F"},
   {"date": "2026-06-25",
    "time": "18:00 UTC-5",
    "team1": "Tunezja",
    "team2": "Holandia",
    "group": "F"},
   {"date": "2026-06-15",
    "time": "12:00 UTC-7",
    "team1": "Belgia",
    "team2": "Egipt",
    "group": "G"},
   {"date": "2026-06-15",
    "time": "18:00 UTC-7",
    "team1": "Iran",
    "team2": "Nowa Zelandia",
    "group": "G"},
   {"date": "2026-06-21",
    "time": "12:00 UTC-7",
    "team1": "Belgia",
    "team2": "Iran",
    "group": "G"},
   {"date": "2026-06-21",
    "time": "18:00 UTC-7",
    "team1": "Nowa Zelandia",
    "team2": "Egipt",
    "group": "G"},
   {"date": "2026-06-26",
    "time": "20:00 UTC-7",
    "team1": "Egipt",
    "team2": "Iran",
    "group": "G"},
   {"date": "2026-06-26",
    "time": "20:00 UTC-7",
    "team1": "Nowa Zelandia",
    "team2": "Belgia",
    "group": "G"},
   {"date": "2026-06-15",
    "time": "12:00 UTC-4",
    "team1": "Hiszpania",
    "team2": "Wyspy Zielonego Przylądka",
    "group": "H"},
   {"date": "2026-06-15",
    "time": "18:00 UTC-4",
    "team1": "Arabia Saudyjska",
    "team2": "Urugwaj",
    "group": "H"},
   {"date": "2026-06-21",
    "time": "12:00 UTC-4",
    "team1": "Hiszpania",
    "team2": "Arabia Saudyjska",
    "group": "H"},
   {"date": "2026-06-21",
    "time": "18:00 UTC-4",
    "team1": "Urugwaj",
    "team2": "Wyspy Zielonego Przylądka",
    "group": "H"},
   {"date": "2026-06-26",
    "time": "19:00 UTC-5",
    "team1": "Wyspy Zielonego Przylądka",
    "team2": "Arabia Saudyjska",
    "group": "H"},
   {"date": "2026-06-26",
    "time": "18:00 UTC-6",
    "team1": "Urugwaj",
    "team2": "Hiszpania",
    "group": "H"},
   {"date": "2026-06-16",
    "time": "15:00 UTC-4",
    "team1": "Francja",
    "team2": "Senegal",
    "group": "I"},
   {"date": "2026-06-16",
    "time": "18:00 UTC-4",
    "team1": "Irak",
    "team2": "Norwegia",
    "group": "I"},
   {"date": "2026-06-22",
    "time": "17:00 UTC-4",
    "team1": "Francja",
    "team2": "Irak",
    "group": "I"},
   {"date": "2026-06-22",
    "time": "20:00 UTC-4",
    "team1": "Norwegia",
    "team2": "Senegal",
    "group": "I"},
   {"date": "2026-06-26",
    "time": "15:00 UTC-4",
    "team1": "Norwegia",
    "team2": "Francja",
    "group": "I"},
   {"date": "2026-06-26",
    "time": "15:00 UTC-4",
    "team1": "Senegal",
    "team2": "Irak",
    "group": "I"},
   {"date": "2026-06-16",
    "time": "20:00 UTC-5",
    "team1": "Argentyna",
    "team2": "Algieria",
    "group": "J"},
   {"date": "2026-06-16",
    "time": "21:00 UTC-7",
    "team1": "Austria",
    "team2": "Jordania",
    "group": "J"},
   {"date": "2026-06-22",
    "time": "12:00 UTC-5",
    "team1": "Argentyna",
    "team2": "Austria",
    "group": "J"},
   {"date": "2026-06-22",
    "time": "20:00 UTC-7",
    "team1": "Jordania",
    "team2": "Algieria",
    "group": "J"},
   {"date": "2026-06-27",
    "time": "21:00 UTC-5",
    "team1": "Algieria",
    "team2": "Austria",
    "group": "J"},
   {"date": "2026-06-27",
    "time": "21:00 UTC-5",
    "team1": "Jordania",
    "team2": "Argentyna",
    "group": "J"},
   {"date": "2026-06-17",
    "time": "12:00 UTC-5",
    "team1": "Portugalia",
    "team2": "Kongo",
    "group": "K"},
   {"date": "2026-06-17",
    "time": "20:00 UTC-6",
    "team1": "Uzbekistan",
    "team2": "Kolumbia",
    "group": "K"},
   {"date": "2026-06-23",
    "time": "12:00 UTC-5",
    "team1": "Portugalia",
    "team2": "Uzbekistan",
    "group": "K"},
   {"date": "2026-06-23",
    "time": "20:00 UTC-6",
    "team1": "Kolumbia",
    "team2": "Kongo",
    "group": "K"},
   {"date": "2026-06-27",
    "time": "19:30 UTC-4",
    "team1": "Kolumbia",
    "team2": "Portugalia",
    "group": "K"},
   {"date": "2026-06-27",
    "time": "19:30 UTC-4",
    "team1": "Kongo",
    "team2": "Uzbekistan",
    "group": "K"},
   {"date": "2026-06-17",
    "time": "15:00 UTC-5",
    "team1": "Anglia",
    "team2": "Chorwacja",
    "group": "L"},
   {"date": "2026-06-17",
    "time": "19:00 UTC-4",
    "team1": "Ghana",
    "team2": "Panama",
    "group": "L"},
   {"date": "2026-06-23",
    "time": "16:00 UTC-4",
    "team1": "Anglia",
    "team2": "Ghana",
    "group": "L"},
   {"date": "2026-06-23",
    "time": "19:00 UTC-4",
    "team1": "Panama",
    "team2": "Chorwacja",
    "group": "L"},
   {"date": "2026-06-27",
    "time": "17:00 UTC-4",
    "team1": "Panama",
    "team2": "Anglia",
    "group": "L"},
   {"date": "2026-06-27",
    "time": "17:00 UTC-4",
    "team1": "Chorwacja",
    "team2": "Ghana",
    "group": "L"}
    ]
}